-- H2 2.3.232;
;
CREATE USER IF NOT EXISTS "SA" SALT '40e25bf312a1a3a8' HASH 'e456f32641a24563175ed1615b8fc54f82cb4b01fde40fe7739a044bc3b9c3ac' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."APP_USERS"(
                                            "IS_ADMIN" BOOLEAN NOT NULL,
                                            "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
                                            "EMAIL" CHARACTER VARYING(255),
                                            "FIRST_NAME" CHARACTER VARYING(255),
                                            "LAST_NAME" CHARACTER VARYING(255),
                                            "PASSWORD" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4A" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.APP_USERS;
INSERT INTO "PUBLIC"."APP_USERS" VALUES
    (TRUE, 1, 'admin@email.com', 'Matias', 'Acosta', '$2a$10$Ypk8uz0GAfjpV7.cDYjF3u0NtRx5O6W4sydZfwFGHlYVtQuE7ONQa');
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
                                          "IS_FREE_SHIPPING" BOOLEAN,
                                          "PRICE" FLOAT(53),
                                          "PRICE_DISCOUNT_PERCENTAGE" INTEGER,
                                          "DESCRIPTION" CHARACTER VARYING,
                                          "ID" CHARACTER VARYING(255) NOT NULL,
                                          "NAME" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT;
INSERT INTO "PUBLIC"."PRODUCT" VALUES
                                   (TRUE, 873895.07, 13, U&'Homem N\00f3s Masculino  \000aEau De Parfum  \000aNatura  \000aContenido: 100ml  \000a\000aPerfume Natura Homem N\00f3s, una fragancia dise\00f1ada para el hombre moderno que busca expresar su autenticidad y carisma. Este Eau Parfum de la reconocida marca Natura ofrece una experiencia olfativa \00fanica, ideal para quienes valoran la elegancia y la sofisticaci\00f3n en cada detalle de su vida.  \000a\000aLa l\00ednea Homem se caracteriza por su enfoque en la masculinidad contempor\00e1nea, y N\00f3s no es la excepci\00f3n. Con un aroma que evoca la frescura y la fuerza, este perfume se convierte en un aliado perfecto para cualquier ocasi\00f3n, ya sea un d\00eda en la oficina o una salida nocturna.  \000a\000aLa duraci\00f3n de la fragancia asegura que su esencia perdure a lo largo del d\00eda, brindando una sensaci\00f3n de confianza y bienestar. Adem\00e1s, Natura se compromete con la sostenibilidad, ofreciendo un producto libre de crueldad y vegano, lo que lo convierte en una elecci\00f3n consciente para el consumidor actual.  \000a\000aSum\00e9rgete en la experiencia de Natura Homem N\00f3s y permite que su aroma te acompa\00f1e en cada paso, reflejando tu personalidad y estilo de vida. Este perfume es m\00e1s que una fragancia; es una declaraci\00f3n de intenciones para el hombre que sabe lo que quiere.', 'MLA49315128', 'Homem Nos Natura 100ml - Masculino - Edp 30% Off - Prt Biene'),
                                   (FALSE, 966132.86, 20, U&'Este producto combina la potencia y la capacidad de una computadora con la versatilidad y facilidad de uso que solo un iPad puede brindar. Realizar varias tareas a la vez, como editar documentos mientras busc\00e1s informaci\00f3n en internet o sacarte una selfie, es sumamente sencillo. Como si esto fuera poco, tambi\00e9n ofrece la posibilidad de descargar desde la App Store cientos de aplicaciones creadas para pintar, dibujar, escuchar m\00fasica y \00a1mucho m\00e1s!', 'MLA22986401', 'iPad Apple iPad Pro 2018');
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_ATTRIBUTES"(
                                                     "ATTRIBUTE_VALUE" CHARACTER VARYING(255),
                                                     "NAME" CHARACTER VARYING(255),
                                                     "PRODUCT_ID" CHARACTER VARYING(255) NOT NULL
);
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_ATTRIBUTES;
INSERT INTO "PUBLIC"."PRODUCT_ATTRIBUTES" VALUES
                                              ('Natura', 'Marca', 'MLA49315128'),
                                              ('Homem', U&'L\00ednea', 'MLA49315128'),
                                              (U&'N\00f3S', 'Nombre del perfume', 'MLA49315128'),
                                              ('Hombre', U&'G\00e9nero', 'MLA49315128'),
                                              ('Eau Parfum', 'Tipo de perfume', 'MLA49315128'),
                                              ('Spray', U&'Formato de aplicaci\00f3n', 'MLA49315128'),
                                              ('100 mL', 'Volumen de la unidad', 'MLA49315128'),
                                              ('No', 'Es recargable', 'MLA49315128'),
                                              ('Brasil', U&'Pa\00eds de origen', 'MLA49315128'),
                                              (U&'S\00ed', 'Es libre de crueldad', 'MLA49315128'),
                                              (U&'S\00ed', 'Es vegano', 'MLA49315128'),
                                              (U&'S\00ed', 'Es libre de alcohol', 'MLA49315128'),
                                              ('Apple', 'Marca', 'MLA22986401'),
                                              ('iPad', U&'L\00ednea', 'MLA22986401'),
                                              ('iPad Pro', 'Modelo', 'MLA22986401'),
                                              ('2018', U&'Versi\00f3n', 'MLA22986401'),
                                              ('63571801993', U&'Homologaci\00f3n Anatel N\00ba', 'MLA22986401');
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_PICTURES"(
                                                   "PRODUCT_ID" CHARACTER VARYING(255) NOT NULL,
                                                   "URL" CHARACTER VARYING(255)
);
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_PICTURES;
INSERT INTO "PUBLIC"."PRODUCT_PICTURES" VALUES
                                            ('MLA49315128', 'https://http2.mlstatic.com/D_NQ_NP_977497-MLA84238785726_052025-F.jpg'),
                                            ('MLA49315128', 'https://http2.mlstatic.com/D_NQ_NP_961163-MLA84535725035_052025-F.jpg'),
                                            ('MLA22986401', 'https://http2.mlstatic.com/D_NQ_NP_784225-MLU77660440505_072024-F.jpg'),
                                            ('MLA22986401', 'https://http2.mlstatic.com/D_NQ_NP_656800-MLU77443484640_072024-F.jpg'),
                                            ('MLA22986401', 'https://http2.mlstatic.com/D_NQ_NP_702770-MLU77443484644_072024-F.jpg'),
                                            ('MLA22986401', 'https://http2.mlstatic.com/D_NQ_NP_924330-MLU75329999576_032024-F.jpg');
CREATE MEMORY TABLE "PUBLIC"."PURCHASE"(
                                           "TOTAL" FLOAT(53),
                                           "DATE" TIMESTAMP(6),
                                           "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
                                           "USER_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PURCHASE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASE;
CREATE MEMORY TABLE "PUBLIC"."PURCHASE_ITEM"(
                                                "AMOUNT" INTEGER,
                                                "SUB_TOTAL" FLOAT(53),
                                                "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
                                                "PURCHASE_ID" BIGINT,
                                                "PRODUCT_ID" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."PURCHASE_ITEM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASE_ITEM;
CREATE MEMORY TABLE "PUBLIC"."QUESTION"(
                                           "CREATED_AT" TIMESTAMP(6),
                                           "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
                                           "USER_ID" BIGINT NOT NULL,
                                           "COMMENT" CHARACTER VARYING NOT NULL,
                                           "PRODUCT_ID" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.QUESTION;
CREATE MEMORY TABLE "PUBLIC"."REVIEW"(
                                         "RATING" INTEGER,
                                         "CREATED_AT" TIMESTAMP(6),
                                         "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
                                         "USER_ID" BIGINT NOT NULL,
                                         "COMMENT" CHARACTER VARYING,
                                         "PRODUCT_ID" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8F" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REVIEW;
CREATE MEMORY TABLE "PUBLIC"."USER_FAVORITE_PRODUCTS"(
                                                         "USER_ID" BIGINT NOT NULL,
                                                         "PRODUCT_ID" CHARACTER VARYING(255) NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_FAVORITE_PRODUCTS;
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" CHECK(("RATING" <= 5)
    AND ("RATING" >= 1)) NOCHECK;
ALTER TABLE "PUBLIC"."APP_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE NULLS DISTINCT ("EMAIL");
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."FKQXUUSYJOOUHXDKPMFHF6LP87W" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FKTGL4OFJB2RQPWP8FLQPFOQN0I" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PURCHASE_ITEM" ADD CONSTRAINT "PUBLIC"."FKQ69APAM78DBI0CGGL37GE6AUF" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_ATTRIBUTES" ADD CONSTRAINT "PUBLIC"."FK95NQSY6PR19OPYU092FBWDR74" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PURCHASE" ADD CONSTRAINT "PUBLIC"."FKK4COHGPBNK2S72360TO676EPF" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USER_FAVORITE_PRODUCTS" ADD CONSTRAINT "PUBLIC"."FKS46UAN2V3BATB2OYGLARXCOGM" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PURCHASE_ITEM" ADD CONSTRAINT "PUBLIC"."FK1MNCC5YAORE1SIBGPJ3JC4A7U" FOREIGN KEY("PURCHASE_ID") REFERENCES "PUBLIC"."PURCHASE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."FKR27H1QC056HX8LC60NVGYHW64" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."FKIYOF1SINDB9QIQR9O8NPJ8KLT" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRODUCT_PICTURES" ADD CONSTRAINT "PUBLIC"."FKHHRQWWVQ0V1PGTLO5JT943UH2" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USER_FAVORITE_PRODUCTS" ADD CONSTRAINT "PUBLIC"."FKL6AT82XBNNQ1W6SYJ7WN6YDXH" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;
